# Generated by Django 3.1.7 on 2021-09-18 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesPerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro', models.PositiveSmallIntegerField(default=9)),
                ('pe', models.PositiveSmallIntegerField(default=18)),
                ('so', models.PositiveSmallIntegerField(default=12)),
                ('mt', models.PositiveSmallIntegerField(default=180)),
                ('pt', models.PositiveSmallIntegerField(default=7)),
                ('ma', models.PositiveSmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('leave_period', models.CharField(choices=[('FIRSTHALF', 'First Half'), ('SECHALF', 'Second Half')], default='FIRSTHALF', max_length=9)),
                ('num_days', models.FloatField(default=0)),
                ('reason', models.CharField(choices=[('PERSONAL', 'Personal Full Day'), ('SICK', 'Sick Full Day'), ('MATERNITY', 'Maternity'), ('PATERNITY', 'Paternity'), ('MARRIAGE', 'Marriage'), ('LOSSOFPAY', 'Loss of Pay Full Day')], default='PERSONAL', max_length=9)),
                ('approved_date', models.DateField(auto_now=True)),
                ('add_date', models.DateField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('approver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=75)),
                ('role', models.BinaryField()),
                ('rollover', models.PositiveSmallIntegerField(default=0)),
                ('lm_start_date', models.DateField()),
                ('approver', models.BooleanField(default=False)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('approver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_approver', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaveman.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaveman.region')),
            ],
        ),
    ]
