# Generated by Django 3.1.7 on 2021-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavesperyear',
            old_name='pe',
            new_name='pl',
        ),
        migrations.RenameField(
            model_name='leavesperyear',
            old_name='so',
            new_name='sl',
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='ma',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='records',
            name='leave_period',
            field=models.CharField(choices=[('FIRHALF', 'First Half'), ('SECHALF', 'Second Half')], default='FIRHALF', max_length=9),
        ),
        migrations.AlterField(
            model_name='records',
            name='reason',
            field=models.CharField(choices=[('PERFD', 'Personal'), ('PERHD', 'Personal (Half Day)'), ('SICFD', 'Sick'), ('SICHD', 'Sick (Half Day)'), ('MATER', 'Maternity'), ('PATER', 'Paternity'), ('MARRY', 'Marriage'), ('LOPFD', 'Loss of Pay'), ('LOPHD', 'Loss of Pay (Half Day)')], default='PERFD', max_length=18),
        ),
    ]
