# Generated by Django 3.1.7 on 2021-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0002_auto_20210928_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesperyear',
            name='eplm',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='leavesperyear',
            name='eslm',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='leavesperyear',
            name='mplcb',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='leavesperyear',
            name='mpleb',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='leavesperyear',
            name='mpscb',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='leavesperyear',
            name='mpseb',
            field=models.FloatField(default=5.0),
        ),
    ]
