# Generated by Django 3.1.7 on 2021-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0003_auto_20210928_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.BinaryField(default=True),
        ),
    ]
