# Generated by Django 3.1.7 on 2021-09-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0004_auto_20210929_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='num_days',
            field=models.FloatField(default=1),
        ),
    ]
