# Generated by Django 3.1.7 on 2021-10-01 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaveman', '0005_auto_20210929_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={'verbose_name': 'Holidays for Different Regions', 'verbose_name_plural': 'Holidays for Different Regions'},
        ),
        migrations.AlterModelOptions(
            name='leavesperyear',
            options={'verbose_name': 'Official Leave Policy Numbers', 'verbose_name_plural': 'Official Leave Policy Numbers'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Employee/Consultant Profile', 'verbose_name_plural': 'Employee/Consultant Profile'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Leave Records', 'verbose_name_plural': 'Leave Records'},
        ),
        migrations.RemoveField(
            model_name='records',
            name='cancelled',
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='eplm',
            field=models.FloatField(default=1.5, verbose_name='Earned Personal Leave/month'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='eslm',
            field=models.FloatField(default=1.0, verbose_name='Earned Sick Leave/month'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='ma',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Marriage'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='mplcb',
            field=models.FloatField(default=3.0, verbose_name='Max. Personal Leave(Borrow/Consultant)'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='mpleb',
            field=models.FloatField(default=5.0, verbose_name='Max. Personal Leave(Borrow/Employee)'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='mpscb',
            field=models.FloatField(default=3.0, verbose_name='Max. Sick Leave(Borrow/Consultant)'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='mpseb',
            field=models.FloatField(default=5.0, verbose_name='Max. Sick Leave(Borrow/Employee)'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='mt',
            field=models.PositiveSmallIntegerField(default=180, verbose_name='Maternity Leave'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='pl',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Max. Personal Leave/year'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='pt',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Paternity Leave'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='ro',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Rollover'),
        ),
        migrations.AlterField(
            model_name='leavesperyear',
            name='sl',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Max. Sick Leave/year'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='approver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_approver', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lm_start_date',
            field=models.DateField(verbose_name='Start Date(leave calculation)'),
        ),
        migrations.AlterField(
            model_name='records',
            name='approver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='records',
            name='from_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='records',
            name='num_days',
            field=models.FloatField(default=0),
        ),
    ]
