# Generated by Django 3.1.7 on 2021-10-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0006_auto_20211001_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
