# Generated by Django 3.1.7 on 2021-10-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0007_records_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='cancelled',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
