# Generated by Django 3.1.7 on 2021-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0008_auto_20211007_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
