# Generated by Django 3.2.9 on 2021-11-26 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leaveman', '0009_auto_20211007_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default=uuid.UUID('cbc4bfcb-91a7-405b-b4aa-68798ec4c775'), max_length=500),
        ),
    ]
